// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn3sfg74rNX9ozT9-KHIUkJXZ15P-hDhA',
    appId: '1:701723855494:web:0ba8233ad1618bbd709f07',
    messagingSenderId: '701723855494',
    projectId: 'han-bab',
    authDomain: 'han-bab.firebaseapp.com',
    storageBucket: 'han-bab.appspot.com',
    measurementId: 'G-9QBDW7Q4LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGTQ1LxUS-TC61TZjKnCwfKNJbJS3Uzug',
    appId: '1:701723855494:android:135a994af83e2b5e709f07',
    messagingSenderId: '701723855494',
    projectId: 'han-bab',
    storageBucket: 'han-bab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Sz2uPpPNl3te0kTgxZnEuRZrD_avz6c',
    appId: '1:701723855494:ios:b57a1e5176ec8ae6709f07',
    messagingSenderId: '701723855494',
    projectId: 'han-bab',
    storageBucket: 'han-bab.appspot.com',
    iosClientId: '701723855494-a68dbuo6k8rfkh74thuje189kvktbv42.apps.googleusercontent.com',
    iosBundleId: 'com.example.hanBab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Sz2uPpPNl3te0kTgxZnEuRZrD_avz6c',
    appId: '1:701723855494:ios:4db9c4680b65515f709f07',
    messagingSenderId: '701723855494',
    projectId: 'han-bab',
    storageBucket: 'han-bab.appspot.com',
    iosClientId: '701723855494-ssvg92b0tn2fa3mcbeidodj0s5t8lr34.apps.googleusercontent.com',
    iosBundleId: 'com.example.hanBab.RunnerTests',
  );
}
